<script src="{{ asset('js/jquery-3.6.0.min.js') }}"></script><!-- JQUERY.MIN JS -->
<script src="{{ asset('js/popper.min.js') }}"></script><!-- POPPER.MIN JS -->
<script src="{{ asset('js/bootstrap.min.js') }}"></script><!-- BOOTSTRAP.MIN JS -->
<script src="{{ asset('js/magnific-popup.min.js') }}"></script><!-- MAGNIFIC-POPUP JS -->
<script src="{{ asset('js/waypoints.min.js') }}"></script><!-- WAYPOINTS JS -->
<script src="{{ asset('js/counterup.min.js') }}"></script><!-- COUNTERUP JS -->
<script src="{{ asset('js/waypoints-sticky.min.js') }}"></script><!-- STICKY HEADER -->
<script src="{{ asset('js/isotope.pkgd.min.js') }}"></script><!-- MASONRY  -->
<script src="{{ asset('js/imagesloaded.pkgd.min.js') }}"></script><!-- MASONRY  -->
<script src="{{ asset('js/owl.carousel.min.js') }}"></script><!-- OWL  SLIDER  -->
<script src="{{ asset('js/slick.min.js') }}"></script><!-- SLICK  Slider  -->
<script src="{{ asset('js/theia-sticky-sidebar.js') }}"></script><!-- STICKY SIDEBAR  -->
<script src="{{ asset('js/jquery.bootstrap-touchspin.js') }}"></script><!-- FORM JS -->
<script src="{{ asset('js/lc_lightbox.lite.js')}}"></script><!-- IMAGE POPUP -->
<script src="{{ asset('js/bootstrap-slider.min.js') }}"></script><!-- Form js -->
<script src="{{ asset('js/swiper-bundle.min.js') }}"></script><!-- Swiper js -->
<script src="{{ asset('js/jquery.bgscroll.js') }}"></script><!-- BACKGROUND SCROLL -->
<script src="{{ asset('js/custom.js') }}"></script><!-- CUSTOM FUCTIONS  -->
